POST {{origin}}/api/baby
Content-Type: application/json

{
  "name": "ELEVEN",
  "bornAt": "2023-10-05 16:23:00",
  "gender": 0
}

### Get baby detail
GET {{origin}}/api/baby/1


### Update baby
@id = 1
PATCH {{origin}}/api/baby/{{id}}
Content-Type: application/json

{
  "avatarUploadId": 30
}
