### query all event-log
GET {{origin}}/api/event-log

### query event-log by name
GET {{origin}}/api/event-log?eventName=Weigh

### query event-log by date
GET {{origin}}/api/event-log?date=2023-12-05

### query distinct event-log
GET {{origin}}/api/event-log/distinct

### query distinct event-log by date
GET {{origin}}/api/event-log/distinct?date=2023-12-06

### create event-log
POST {{origin}}/api/event-log
Content-Type: application/json

{
  "eventName": "Weigh",
  "extra": {
    "weight": 5.5
  },
  "eventTime": "2023-12-05T00:00:00.000Z"
}

### delete event-log
DELETE {{origin}}/api/event-log/23
