### create sample event
POST {{origin}}/api/event
Content-Type: application/json

< ./events.json

### get all events
GET {{origin}}/api/event

### patch event
PATCH {{origin}}/api/event
Content-Type: application/json

< ./event.supplement.json

### batch patch events
PATCH {{origin}}/api/event
Content-Type: application/json

< ./events.json

### patch event
PATCH {{origin}}/api/event
Content-Type: application/json

< ./event.diaper.json


