### Create a test bucket
POST {{origin}}/api/bucket
Content-Type: application/json

{
  "name": "test",
  "domain": "test-r2.littleeleven.com"
}

### Create a product bucket
POST {{origin}}/api/bucket
Content-Type: application/json

{
  "name": "eleven",
  "domain": "r2.littleeleven.com"
}

### Query a bucket
GET {{origin}}/api/bucket/test
