### upload image
POST {{origin}}/api/r2/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="play.jpeg"
Content-Type: image/jpeg

< ./play.jpeg
--WebAppBoundary

### upload video
POST {{origin}}/api/r2/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="video.mp4"
Content-Type: video/mp4

< ./video.mp4
--WebAppBoundary

### get upload
GET {{origin}}/api/r2/upload/c95e79ba322c3c4a48edbfacad41c0c7071795c6adf5fb94778ff4ae46d2dea2
