### upload image
POST {{origin}}/api/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="play.jpeg"
Content-Type: image/jpeg

< ./play.jpeg
--WebAppBoundary

### upload video
POST {{origin}}/api/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="video.mp4"
Content-Type: video/mp4

< ./video.mp4
--WebAppBoundary
